<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:clar="Claro.SelfCareManagement.Services.Entities.Contracts" xmlns:clar1="http://schemas.datacontract.org/2004/07/Claro.SelfCareManagement.Services.Entities.Messages">
  <soapenv:Header>
     <clar:HeaderAutenticacion>
        <clar1:contraseñaAutenticacion>Mi2018ClaroCo*$lo.$m2b1ia</clar1:contraseñaAutenticacion>
        <clar1:tipoCanalID><?=isset($data->tipoCanalID)?2:1?></clar1:tipoCanalID>
        <clar1:usuarioAutenticacion>Mi$2019.$COL*$1C$LA$0</clar1:usuarioAutenticacion>
     </clar:HeaderAutenticacion>
  </soapenv:Header>
  <soapenv:Body>
     <clar:ComprarPaquetePartidoRequest>
        <clar:paquetePartido>
           <clar1:codigoContrato><?=$data->codigoContrato?></clar1:codigoContrato>
           <clar1:codigoPartido><?=$data->codigoPartido?></clar1:codigoPartido>
           <clar1:customerID><?=$data->customerID?></clar1:customerID>
           <clar1:fechaHoraInicio><?=$data->fechaHoraInicio?></clar1:fechaHoraInicio>
           <clar1:nombreUsuario><?=$data->nombreUsuario?></clar1:nombreUsuario>
           <clar1:numeroCuenta><?=$data->AccountId?></clar1:numeroCuenta>
           <clar1:tipoCuentaID><?=$data->LineOfBusiness?></clar1:tipoCuentaID>
        </clar:paquetePartido>
     </clar:ComprarPaquetePartidoRequest>
  </soapenv:Body>
</soapenv:Envelope>