<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:user="http://xmlns.oracle.com/schema/RSCustomerDataOTT/userProfileOtt" xmlns:v1="http://www.amx.com/co/schema/mobile/common/aplicationIntegration/Comunes/v1.0" xmlns:cus="http://TargetNamespace.com/customerDataOtt_queryOtt_request">
   <soapenv:Header>
      <user:NotifySOAPHeader>
         <!--Optional:-->
         <user:TransId/>
         <user:Username>PA00003102</user:Username>
         <user:Password>aMc0Co3!</user:Password>
      </user:NotifySOAPHeader>
      <v1:headerRequest>
         <v1:channel/>
         <!--Optional:-->
         <v1:transactionId/>
         <!--Optional:-->
         <v1:ipApplication/>
      </v1:headerRequest>
   </soapenv:Header>
   <soapenv:Body>
      <cus:Root-Element>
         <cus:queryOttRequest>
            <cus:invokeMethod>consultardispositivoscliente</cus:invokeMethod>
            <cus:correlatorId>00000232550e8400e29b41d4a716446655440799</cus:correlatorId>
            <cus:countryId>CO</cus:countryId>
            <cus:employeeId>9984</cus:employeeId>
            <cus:origin>MI_CLARO</cus:origin>
            <!--Optional:-->
            <cus:serviceName>consultardispositivoscliente</cus:serviceName>
            <cus:providerId>PA00002812</cus:providerId>
            <cus:iccidManager>AMCOCO</cus:iccidManager>
            <!--Zero or more repetitions:-->
            <cus:extensionInfo>
               <cus:key>CUSTOMERID</cus:key>
               <cus:value><?=$data->value?></cus:value>
            </cus:extensionInfo>
         </cus:queryOttRequest>
      </cus:Root-Element>
   </soapenv:Body>
</soapenv:Envelope>